package: stats
version: dev

page:
  title: 'Statistiken'
  icon: rex-icon fa-line-chart
  subpages:
    stats:
      title: Statistiken
    pages: 
      title: Seiten
    settings: 
      title: Einstellungen

requires:
  redaxo: '^5.11'
  php:
    version: '>=7.1'

default_config:
    pagestats_ignored_paths: ''
    pagestats_visit_duration: 30