package: statistics
version: dev
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/statistics

page:
  title: 'Statistiken'
  icon: rex-icon fa-line-chart
  perm: stats[]
  subpages:
    stats:
      title: Statistiken
      icon: rex-icon fa-pie-chart
    pages: 
      title: Seitenaufrufe
      icon: rex-icon fa-file-text-o
    referer: 
      title: Verweise
      icon: rex-icon fa-external-link
    settings: 
      title: Einstellungen
      perm: admin
      icon: rex-icon fa-cog

requires:
  redaxo: '^5.11'
  packages:
    yrewrite: '^2.7'
  php:
    version: '>=7.1'

default_config:
    pagestats_ignored_paths: ''
    pagestats_ignored_ips: ''
    pagestats_visit_duration: 30
    pagestats_chart_padding_bottom: 90
