package: statistics
version: dev
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/redaxo_analytics

page:
  title: 'Statistiken'
  icon: rex-icon fa-line-chart
  perm: stats[]
  subpages:
    stats:
      title: Statistiken
    pages: 
      title: Seiten
    media: 
      title: Medien
    referer: 
      title: Referer
    settings: 
      title: Einstellungen
      perm: admin

requires:
  redaxo: '^5.11'
  php:
    version: '>=7.1'

default_config:
    pagestats_ignored_paths: ''
    pagestats_ignored_ips: ''
    pagestats_visit_duration: 30
    pagestats_chart_padding_bottom: 90
