package: stats
version: dev

page:
  title: 'Statistiken'
  icon: rex-icon fa-line-chart
  subpages:
    stats:
      title: Statistiken
    pages: 
      title: Seiten
    settings: 
      title: Einstellungen

requires:
  redaxo: '^5.12'
  php:
    version: '>=7.1'